### ISSUE TITLE
Introducing new node to existing network?

### ISSUE THREAD

**Issue by ml3958** [micans/mcl#1]
Hi, 

Thanks so much for developing this amazing method.  I have used mcl on my very large protein networks (~10milion proteins) and It works pretty. I have two questions: 

1. I want to expand to large proteins, however the *.abc* file (~2T) has exceed my system RAM, and seems to to kill the `maxload` process. 

2. Is there a way to add new proteins into the existing network? If so, I can solve the first problem and potentially skip the bulk of `mcl`, which took days to run.

Any input would be greatly appreciated.
Best, Menghan

**Comment by micans** [comment]
Hi Menghan,

Thank you for your kind words. It is possible to speed up/optimise the loading of the matrix, but I have some doubts; is it the case that you want to add proteins into the existing network and then re-cluster (A), or do you want to add the proteins to the clustering (B) (as you write “potentially skip the bulk of mcl”). If it is (A) then I can probably make a recipe that helps.

Best wishes,
Stijn

From: Menghan Liu ***@***.***>
Reply-To: micans/mcl ***@***.***>
Date: Monday, 1 November 2021 at 14:53
To: micans/mcl ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [micans/mcl] Introducing new node to existing network? (Issue #1) [EXT]


Hi,

Thanks so much for developing this amazing method. I have used mcl on my very large protein networks (~10milion proteins) and It works pretty. I have two questions:

  1.  I want to expand to large proteins, however the .abc file (~2T) has exceed my system RAM, and seems to to kill the maxload process.
  2.  Is there a way to add new proteins into the existing network? If so, I can solve the first problem and potentially skip the bulk of mcl, which took days to run.

Any input would be greatly appreciated.
Best, Menghan

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_micans_mcl_issues_1&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=hInWKPd_m4PWFkdglr0s_ajCZYBRBuC-e9VWqp87EkY&m=J0GU69LGnByf8nSBMmU9vttqFE4OEzNUQ5cWA0wOKlYndAZ1jPw4bWG4RW-OTVYp&s=3BXQ5g97z0d_CnSA75gfdrlo-7H0rJJBQz5MZF1Zqnw&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAZWX4BOC7YJ7NVEPKCPCSLUJ2SVHANCNFSM5HEG2BKQ&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=hInWKPd_m4PWFkdglr0s_ajCZYBRBuC-e9VWqp87EkY&m=J0GU69LGnByf8nSBMmU9vttqFE4OEzNUQ5cWA0wOKlYndAZ1jPw4bWG4RW-OTVYp&s=YGD9UFUpLACDD3i4_YFt4hQPBB8U1bW7XlZMqciCCIY&e=>.
Triage notifications on the go with GitHub Mobile for iOS [apps.apple.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=hInWKPd_m4PWFkdglr0s_ajCZYBRBuC-e9VWqp87EkY&m=J0GU69LGnByf8nSBMmU9vttqFE4OEzNUQ5cWA0wOKlYndAZ1jPw4bWG4RW-OTVYp&s=YDF1QsA8r_rW9dBTJyBXEUEr7aKQENH6lIqAnvpKU8A&e=> or Android [play.google.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=hInWKPd_m4PWFkdglr0s_ajCZYBRBuC-e9VWqp87EkY&m=J0GU69LGnByf8nSBMmU9vttqFE4OEzNUQ5cWA0wOKlYndAZ1jPw4bWG4RW-OTVYp&s=MWPh_vCE0tb-JhMGyPVjJBg8RQS6ZVG8g3DavJveJo8&e=>.



-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by ml3958** [comment]
Thanks for your prompt reply, Stijn.

I was hoping to do (B) initially because of the fact that adding new proteins would exceed my system RAM, thus cause problem for `maxload` and `mcl`. Is it a reasonable concern? I would love to hear your solution to (A) as well !

Thanks, Menghan

**Comment by micans** [comment]
Hi Menghan,

For (A) the mcxload step can be improved I’m pretty sure. Did the abc file (2T) exceed your disk space, rather than your RAM?
It is possible to create an mcl matrix in incremental steps, not needing to feed it all the edges at the same time. I think it should be possible as well to update a matrix for an existing network by adding another matrix that encodes only the new edges.

Also you could give mcl different parameters so that it still runs and does not use as much memory. However, each time you cluster will still be a very big compute job.

For (B) I have a memory that I looked into this at some point; I’ll get back to you about that later. Do send me an e-mail if I don’t get back within a day. We can still e-mail about (A) if you want of course (I can respond quicker).

bw,
Stijn


From: Menghan Liu ***@***.***>
Reply-To: micans/mcl ***@***.***>
Date: Monday, 1 November 2021 at 16:55
To: micans/mcl ***@***.***>
Cc: Stijn van Dongen ***@***.***>, Comment ***@***.***>
Subject: Re: [micans/mcl] Introducing new node to existing network? (Issue #1) [EXT]


Thanks for your prompt reply, Stijn.

I was hoping to do (B) initially because of the fact that adding new proteins would exceed my system RAM, thus cause problem for maxload and mcl. Is it a reasonable concern? I would love to hear your solution to (A) as well !

Thanks, Menghan

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_micans_mcl_issues_1-23issuecomment-2D956404650&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=hInWKPd_m4PWFkdglr0s_ajCZYBRBuC-e9VWqp87EkY&m=sgGhAEtvglVMZa_oAxFKGVDd15m-qe3-ZIIg-RYAEZBtE3W3YshdVb4gdG1Spky5&s=mYlX3s2ufAk-CXky7ibZr5dxAl8Rd6CA4ZEV4Yf2IoU&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAZWX4BPESEEBJMI3YG3OZTUJ3BA7ANCNFSM5HEG2BKQ&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=hInWKPd_m4PWFkdglr0s_ajCZYBRBuC-e9VWqp87EkY&m=sgGhAEtvglVMZa_oAxFKGVDd15m-qe3-ZIIg-RYAEZBtE3W3YshdVb4gdG1Spky5&s=afGWL4fQNwdmy0vuaOs6_DPBq19xP_EUEq1bPlNnHlQ&e=>.
Triage notifications on the go with GitHub Mobile for iOS [apps.apple.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=hInWKPd_m4PWFkdglr0s_ajCZYBRBuC-e9VWqp87EkY&m=sgGhAEtvglVMZa_oAxFKGVDd15m-qe3-ZIIg-RYAEZBtE3W3YshdVb4gdG1Spky5&s=tcQcHdAi0Pmdzx0BupikNMKdL1LwNNRArbXnbuuUsNo&e=> or Android [play.google.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=hInWKPd_m4PWFkdglr0s_ajCZYBRBuC-e9VWqp87EkY&m=sgGhAEtvglVMZa_oAxFKGVDd15m-qe3-ZIIg-RYAEZBtE3W3YshdVb4gdG1Spky5&s=yVO0N0nGcGrE8JJUCbLA4J7rtdwZ6MQzJS7e2JE0mAc&e=>.



-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by ml3958** [comment]
Thanks so much, Stijin. I am looking forward to hearing about (B). If it
works, it will give me so much flexibility of easily adding new genomes
into a existing pipeline/analysis. :-)

For (A), the 2TB abc file is smaller than my disk. My machine has 14T disk
space left and 384GB RAM. I now went back to my log and found the error
message (below), and It seems that my script was killed at the `mcxload`
step. Perhaps I should set a limit on RAM for maxload?

'.................................................. 31832M

.................................................. 31833M

.................................................. 31834M

.................................................. 31835M

.................................................. 31836M

.................................................. 31837M

.................................................. 31838M

..............................................
/mnt/data1/run_02_mcxload.sh: line 27: 10397 Killed                  mcxload
-abc $dir_orthogroup/alignment_evalue_orig.abc -o
$dir_orthogroup/alignment_evalue.mci -write-tab $dir_orthogroup/seq_dic.tab
--stream-neg-log10 -stream-tf 'ceil(400)' --write-binary -ri max' `

Thanks so much, Menghan

**Comment by micans** [comment]
Setting a limit will not help. Perhaps a limit (RAM or time) is in place, and exceeding that limit caused the mcxload process to be killed (or a bug). However, you've run mcl on 10M nodes, and that should be much more memory intensive than mcxload, suggesting it cannot be a limit. It  is difficult to know what to do without more information. Do you run this on a node of a compute cluster?

Regardless of all these considerations, for constructing the matrix I think it would be beneficial to subdivide reading the matrix into different jobs, each constructing a sub-network, then adding the networks together. How many lines are in the big abc file? At least 31,838M I gather. How many nodes would there be in the network? If this is based on something like blast scores, are you already using a cut-off for the weights (disregard edges below a certain log-score)?

Adding nodes to an existing clustering is a bit of a stopgap. By the way, it is a problem that has different solutions (e.g. something like a weighted majority vote), and this is not really to do with mcl. You could conceivably do it yourself; what I once implemented was a simple weighted-vote-like method (I will check if the mcl software provides this).

The more nodes you add to an existing clustering, the more of a stopgap it is. What is the total number of nodes you'd like to have a clustering for; or could it forever grow as new data becomes available?

Sorry, many questions, but with this size of data a good strategy and understanding of the context and requirements really helps, as the compute is so expensive both in time, cpu and RAM.

**Comment by ml3958** [comment]
Thanks so much for the reply. I will try to answer point to point

> Setting a limit will not help. Perhaps a limit (RAM or time) is in place, and exceeding that limit caused the mcxload process to be killed (or a bug). However, you've run mcl on 10M nodes, and that should be much more memory intensive than mcxload, suggesting it cannot be a limit. It is difficult to know what to do without more information. Do you run this on a node of a compute cluster?
> Regardless of all these considerations, for constructing the matrix I think it would be beneficial to subdivide reading the matrix into different jobs, each constructing a sub-network, then adding the networks together. How many lines are in the big abc file? At least 31,838M I gather. How many nodes would there be in the network? If this is based on something like blast scores, are you already using a cut-off for the weights (disregard edges below a certain log-score)?

I ran this on my own workstation (12 core) so it should be limited by time as a a cluster limits job running time. So I am guessing the problem is more with the RAM (384GB). With this current failed job, I have ~19 million nodes, 31,838,930,734 lines in abc file, based blast scores (e^-10 cutoff). The previous successful run was with half of data size. Please let me know if I can provide more info.

> Adding nodes to an existing clustering is a bit of a stopgap. By the way, it is a problem that has different solutions (e.g. something like a weighted majority vote), and this is not really to do with mcl. You could conceivably do it yourself; what I once implemented was a simple weighted-vote-like method (I will check if the mcl software provides this).

I was thinking something similar!  And I completely agree it is a bit stopgap, so I was also thinking to do a pilot analysis to show such suboptimal method (weighted majority vote) is *reasonably* consistent with redoing the mcl. What would be your intuition/experience with the comparison outcome?

> The more nodes you add to an existing clustering, the more of a stopgap it is. What is the total number of nodes you'd like to have a clustering for; or could it forever grow as new data becomes available?

My current thought is that to start with a diverse protein collection (as diverse as possible), and then it would be forever grow as new data are being considered.  

> Sorry, many questions, but with this size of data a good strategy and understanding of the context and requirements really helps, as the compute is so expensive both in time, cpu and RAM.

Thanks so much for your help. I would love to provide more details. This has been such a critical step in my research so I appreciate the existence of mcl and your help :)

**Comment by micans** [comment]
> I ran this on my own workstation (12 core) so time should not be a limiting factor as a a cluster limits job running time. So I am guessing the problem is more with the RAM (384GB). With this current failed job, I have ~19 million nodes, 31,838,930,734 lines in abc file, based blast scores (e^-10 cutoff). The previous successful run was with half of data size. Please let me know if I can provide more info.

Aha so mcxload died after it had parsed all edges. Going from 10M nodes to 19M nodes is quite a big step up; it is safe to assume that 384GB ram is the limiting factor. It seems likely that you would need one of a) bigger hardware b) a different cluster algorithm or c) a diffferent implementation of mcl (e.g. hipMCL, but that will require access to cluster hardware as well and I don't know how easy it is to set it up). 

I checked the node assignment by the way, `clm residue` (shipped with mcl) does that, but requires reading in the full network for all nodes, so that's not useful. Also with a jump from 10M nodes to 19M nodes this approach is not suitable. Have you looked at cluster algorithms like CD-HIT, DBSCAN, OPTICS, or Louvain or Leiden? They probably have lower memory requirements than mcl.

I haven't kept up with the literature and the phletora of existing clustering algorithms. Ensembl families used to use mcl on networks approaching 10M nodes but now they use  the TreeFam HMM library to define clusters.

In your case it might be interesting to do some pre-redundancy pruning to set a certain set of nodes aside and avoid very similar nodes in the network. This of course would be defining your own hybrid clustering algorithm (and this idea is similar to CD-HIT I think).

> I was thinking something similar! And I completely agree it is a bit stopgap, so I was also thinking to do a pilot analysis to show such suboptimal method (weighted majority vote) is _reasonably_ consistent with redoing the mcl. What would be your intuition/experience with the comparison outcome?

My hunch is that this works a bit as long as you're only adding 1 or 2% extra nodes, but certainly not if you double the number of nodes.

> My current thought is that to start with a diverse protein collection (as diverse as possible), and then it would be forever grow as new data are being considered.

A bit related to the remarks about pre-redundancy pruning and CD-HIT above. Have you tried other clustering algorithms?
How quickly does your data grow? After 19M nodes, would the next step be more gradual, e.g. 5% more nodes, or would there again be a jump up?

**Comment by micans** [comment]
Hi sorry slight delay in response.

> I was considering a hybrid approach! I clustered those ~19 million proteins using CD-HIT at 90% identity to ~13 million in a day. So CD-hit definitely is able to reduce the data to the scale that `mcl` can handle. A few things I was considering and wonder what you think:
> 
>     1. how many and how to pick representative sequences for downstream mcl clustering. the longest ones? or most diverse (sequence-level)?

I wonder if a slightly different hybrid approach might work, which is to find a way to break up the network into different parts, using for example single linkage clustering, or perhaps by using CD-HIT to create a network that manages to filter weak edges, then apply single linkage clustering on that, then use MCL on the individual components.

There is a technical aspect to this. Apart from mcl, the underlying library and siblings programs have been designed to deal efficiently with large network manipulations, providing some ways of querying and transforming. Hence there are scripted approaches that would make some of this easy.

The main challenge is to be able to work with the initial big data. I wonder if the mcxload step could be improved, however, with your data the raw result matrix will take 16 bytes per edge (8 bytes per arc); if you specified the edge in both directions in the 'abc' file this would be (31838930734*8)/384000000000 = 66% of your RAM memory (and twice that if the edge was specified only once).

>     2. In general, I always wonder what is the _rule of thumb_ rule practice while using algorithm like CD-HIT that largely considers identity only, but not statistics (i.e., evalue). Since I care about grouping sequences to functionally orthogonal families, my _limited_ experience of using CDhit suggest it produces many small clusters (even at low identity of 60% and high coverage threshold), and orthogonal groups tend to be broken into small subgroups.  I wonder what your take on this as this evaluation is rarely mentioned in past literatures. Not being negative at all, but my conclusion was CD-HIT is not ideal to produce orthogonal families but rather to reduce data redundancy. Therefore,  a hybrid of` CD-HIT` and `mcl` might actually be a great solution for big data with speed and accuracy. Sorry I think I've combined answers to multiple of your questions here.

I don't have experience really with using CD-HIT, so cannot comment on that. Since you mention orthogonal families, have you considered OrthoMCL? I assume you have species annotation?

> > A bit related to the remarks about pre-redundancy pruning and CD-HIT above. Have you tried other clustering algorithms? How quickly does your data grow? After 19M nodes, would the next step be more gradual, e.g. 5% more nodes, or would there again be a jump up?
> 
> After the initial clustering, next step would be gradual-perhaps 0.01% at a time. So one could even think of a three step approach: `CD-HIT` --> `mcl` --> `clm residue`? I have to check how to use `clm residue`. Is there an example somewhere?

There is a manual page (https://micans.org/mcl/src/mcl-latest/doc/clmresidue.html)
I can give a recipe (as it would involve some manipulation of tab files and networks), but perhaps best to do this once the problem of clustering 19M nodes (using linkage+components, or size reduction of some kind) is solved.

**Comment by micans** [comment]
Tied to the previous comment: how about trying one or two approaches to cut the network into smaller components (each could still be, say, up to 5 million nodes) with the purpose of clustering each component separately?
Initially it would be best to see if dividing the network into components is feasible on a test case, say with up to 1M nodes.
