### ISSUE TITLE
Two issues: "nx.to_scipy_sparse_matrix" not exist and the hyperparameter "inflation" not working?

### ISSUE THREAD

**Issue by HsiangHung** [micans/mcl#16]
Hi MCL Community,

I found two issues:

1. In the sample code, nx.to_scipy_sparse_matrix doesn't exist in networkx 3.0. The document needs to be updated to nx.to_scipy_sparse_array.
2. I tried the doc: https://markov-clustering.readthedocs.io/en/latest/readme.html and found different hyperparameter inflation =1.5-2.6 also gave the same results and modularity are different from the doc page: 
![image](https://user-images.githubusercontent.com/13720210/221433452-34e7b140-55a5-42a2-aef3-ac1686d367ed.png)

Also inflation=1.1 and inflation=2.5 gave the same clustering outcome. I think there is a bug. Can you check? Thanks.

**Comment by micans** [comment]
Hello,

I see you have also opened https://github.com/GuyAllard/markov_clustering/issues/37 - that is the correct place for this issue as it pertains to the code in that repository. This repository is an entirely different code base. I will close the issue here, and will participate in https://github.com/GuyAllard/markov_clustering/issues/37 if that is useful. Please note I have not been involved with that code however, and secondly the code does not seem to be actively supported anymore.
If you are not committed to a Python implementation you could give the C implementation here a try, although I understand that this could be inconvenient.

**Comment by micans** [comment]
(Feel free to ask further questions here, but I cannot help with the issue itself)
