### ISSUE TITLE
mcl version 22-282 failing to build under archlinux 

### ISSUE THREAD

**Issue by kbipinkumar** [micans/mcl#17]
i am attempting to package mcl version 22-282 for Archlinux using suggested source tarballs from [mcl homepage](https://micans.org/mcl/index.html). while building using suggested commands the build process stops with following error output

```bash
$ ./configure --prefix /usr
$ make
make  all-recursive
make[1]: Entering directory '/build/mcl/src/mcl-22-282'
Making all in .
make[2]: Entering directory '/build/mcl/src/mcl-22-282'
make[2]: Leaving directory '/build/mcl/src/mcl-22-282'
Making all in img
make[2]: Entering directory '/build/mcl/src/mcl-22-282/img'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/build/mcl/src/mcl-22-282/img'
Making all in graphs
make[2]: Entering directory '/build/mcl/src/mcl-22-282/graphs'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/build/mcl/src/mcl-22-282/graphs'
Making all in doc
make[2]: Entering directory '/build/mcl/src/mcl-22-282/doc'
zoem -d roff -i mcl.azm -o mcl.1
___ [\dofile#2] failed to open file <pud/man.zmm>
___ [zoem] unwound on error/exception
___ [\dofile#2] error (9) occurred while reading file <mcx.zmm>
___ [zoem] unwound on error/exception
make[2]: *** [Makefile:689: mcl.1] Error 9
make[2]: Leaving directory '/build/mcl/src/mcl-22-282/doc'
make[1]: *** [Makefile:383: all-recursive] Error 1
make[1]: Leaving directory '/build/mcl/src/mcl-22-282'
make: *** [Makefile:324: all] Error 2
```
i have both cimfomfa and zoem installed

**Comment by micans** [comment]
Something is not right (as you noticed), but the bigger issue is that the installation process should not be attempting to do anything in the subdirectory doc as the timestamps of the generated (and shipped) documentation are younger than the source files. It should not be necessary to generate the documentation by running zoem. What were the command line invocations you issued before the configure command shown here? Have you looked at the procedure in the script install-this-mcl.sh (in the root of the repository) - is your procedure similar, or, if different, how? A simple thing to try to fix your issue is to just re-extract the mcl source from its tarball and redo things with fresh time-stamps.

**Comment by kbipinkumar** [comment]
Thanks for the input. the issue seems to have gone away when compiling inside clean chroot with sources directly downloaded from mcl releases page

**Comment by micans** [comment]
Excellent, I'll close this issue.
